  
# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - eko-restaurant(Production), Build and deploy DotnetCore app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@azure_current


    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      working-directory: ./EkoRestaurant
      run: dotnet build --configuration Release

    - name: dotnet publish
      working-directory: ./EkoRestaurant
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: ekoRest
        slot-name: Production
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d7a41e73c4984a4d9bb99a51c367d3f1 }}
        package: ${{env.DOTNET_ROOT}}/myapp
